source 'https://rubygems.org'

gem 'rails', '4.0.2'

gem 'sqlite3'
gem 'uglifier', '>= 1.3.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 1.2'
gem 'inherited_resources', '~> 1.4.1'
gem 'haml', '~> 4.0.3'
gem 'formtastic', '~> 2.3.0.rc2'
gem 'rabl'
gem 'cocoon', '~> 1.2.0'
gem 'tire', '~> 0.6.0'
gem 'multi_json', '~>1.8.2'
gem 'erb2haml'
gem 'simple-navigation', '~> 3.11.0'
gem 'nokogiri'
gem 'sass-rails',   '~> 4.0.1'
gem 'coffee-rails', '~> 4.0.1'
gem 'therubyracer'

group :test, :development do
  gem 'rspec-rails', '~> 2.14.0'
  gem 'capybara', '~> 2.1.0'
  gem 'poltergeist', '~> 1.4.1'
  gem 'launchy', '~> 2.3.0'
  gem 'factory_girl_rails', '~> 4.3.0'
  gem 'valid_attribute', '~> 1.3.1'
  gem 'timecop', '~> 0.7.0'
  gem 'pry-rails', '~> 0.3.2'
  gem 'capistrano', '~>2.15.5'
end